#
# Makefile written by Greg Coombe
#
# Date: Thu Oct 29 01:52:10 MST 1998
#

.SUFFIXES: .o .cxx .cc .C .cpp .c
RM     = rm
OBJS   = GLModel.o Useful.o giwarp.o MatrixN.o illuminate.o
EXE    = project


# SGI
#
# Very important note! Execute the command:
# unsetenv LD_LIBRARY_PATH
# to get rid of "soname be.so unable to link under ..."
#
LIBS	= -L/afs/cs.unc.edu/home/coombe/lib/sgi_irix -lglut -lGLU -lXmu -lGL -lX11 -lm
CFLAGS = -g -O2 -D DEBUG -I/afs/cs.unc.edu/home/coombe/include/
CCC    = CC

# Sun
#LIBS	= -lX11 -lXext -lXi -lXmu -lglut -lGLU -lGL -lX11 -lm
#CFLAGS = -g -D DEBUG
#CCC    = g++

# Linux
#CCC    = g++
#CFLAGS = -g -D DEBUG
#INCLUDE   = -I${MY_INC} -I/usr/X11R6/include/ -I/usr/src/linux-2.2.16/include/
#LIBS  = -L/usr/X11R6/lib -lGLU -lGL -lglut -lX11 -lXext -lXi -lXmu -lm

# Now define all of our flags
# CFLAGS = -g -O -Wall
# Use -pg for profiling with gprof
# Use -O{1,2,3} to optimize


${EXE}: ${OBJS}
	${CCC} ${CFLAGS} -o ${EXE} ${OBJS} ${LIBS}

run: ${EXE}
	clear
	${EXE}

tar:
	tar -cvf ${EXE}.tar *.c* *.h* *.c *.h Makefile
	gzip ${EXE}.tar

depend:
	makedepend -Y *.c*

.o .cxx.o .cc.o .C.o .cpp.o .c.o:
	${CCC} ${CFLAGS} ${INCLUDE} -c $<

clean:
	${RM} *.o ${EXE} *~
# DO NOT DELETE

Copy of MatrixN.o: MatrixN.h Useful.h Train.h
GLModel.o: GLModel.h Useful.h MatrixN.h Train.h GSample.h
GLModel.o: GLModel.h Useful.h MatrixN.h Train.h GSample.h
MatrixN.o: MatrixN.h Useful.h Train.h MElementPool.h
MatrixN.o: MatrixN.h Useful.h Train.h
Second Copy of MatrixN.o: MatrixN.h Useful.h Train.h
Useful.o: Useful.h
giwarp.o: illuminate.h GLModel.h Useful.h MatrixN.h Train.h GSample.h
giwarp.o: ColorCycler.h
illuminate.o: illuminate.h GLModel.h Useful.h MatrixN.h Train.h GSample.h
